#!/usr/bin/env python3

from enum import Enum

class KEY_BINDINGS(Enum):
    SUB_MENU_4BY4_SHORT_CUT = 'Ctrl+F'
    SUB_MENU_6BY6_SHORT_CUT = 'Ctrl+S'
    SUB_MENU_CUSTOM_GRID_SHORT_CUT = 'Ctrl+G'
    SUB_MENU_DIFFICULTY_EASY_SHORT_CUT = 'Ctrl+E'
    SUB_MENU_DIFFICULTY_HARD_SHORT_CUT = 'Ctrl+H'
    SUB_MENU_RANDOM_GRID_SHORT_CUT = 'Ctrl+B'
    SUB_MENU_GAME_RULES_SHORT_CUT = 'Ctrl+R'
    SUB_MENU_CREATORS_SHORT_CUT = 'Ctrl+C'
    SUB_MENU_QUIT_SHORT_CUT = 'Ctrl+Q'
