#!/usr/bin/env python3

# import libraries
from enum import Enum

# import configuration file
from src.config import config

# import text file
if   config.language == 'EN': from src.enums.textEnums.EN_textEnum import TEXT_EN as T
elif config.language == 'FR': from src.enums.textEnums.FR_textEnum import TEXT_FR as T

class TEXT(Enum):
    WINDOW_TITLE = T.WINDOW_TITLE.value

    MENU_GRID_TITLE = T.MENU_GRID_TITLE.value
    MENU_PLAY_TITLE = T.MENU_PLAY_TITLE.value
    MENU_ABOUT_TITLE = T.MENU_ABOUT_TITLE.value
    MENU_QUIT_TITLE = T.MENU_QUIT_TITLE.value

    SUB_MENU_4BY4_TITLE = T.SUB_MENU_4BY4_TITLE.value
    SUB_MENU_6BY6_TITLE = T.SUB_MENU_6BY6_TITLE.value
    SUB_MENU_CUSTOM_GRID_TITLE = T.SUB_MENU_CUSTOM_GRID_TITLE.value
    SUB_MENU_DIFFICULTY_EASY_TITLE = T.SUB_MENU_DIFFICULTY_EASY_TITLE.value
    SUB_MENU_DIFFICULTY_HARD_TITLE = T.SUB_MENU_DIFFICULTY_HARD_TITLE.value
    SUB_MENU_RANDOM_GRID_TITLE = T.SUB_MENU_RANDOM_GRID_TITLE.value
    SUB_MENU_GAME_RULES_TITLE = T.SUB_MENU_GAME_RULES_TITLE.value
    SUB_MENU_CREATORS_TITLE = T.SUB_MENU_CREATORS_TITLE.value
    SUB_MENU_QUIT_TITLE = T.SUB_MENU_QUIT_TITLE.value

    HOME_DESCRIPTION = T.HOME_DESCRIPTION.value

    GAME_GRID_COMPLETE_MESSAGE = T.GAME_GRID_COMPLETE_MESSAGE.value
    GAME_GRID_VALID_MESSAGE = T.GAME_GRID_VALID_MESSAGE.value
    GAME_GRID_NOT_VALID_ERROR_MESSAGE = T.GAME_GRID_NOT_VALID_ERROR_MESSAGE.value
    GAME_NUMBERS_DISTRIBUTION_ERROR_MESSAGE = T.GAME_NUMBERS_DISTRIBUTION_ERROR_MESSAGE.value
    GAME_GRID_NOT_FILLED_ERROR_MESSAGE = T.GAME_GRID_NOT_FILLED_ERROR_MESSAGE.value
    GAME_LENGTH_NUMBER_SEQUENCE_ERROR_MESSAGE = T.GAME_LENGTH_NUMBER_SEQUENCE_ERROR_MESSAGE.value
    GAME_LIVES = T.GAME_LIVES.value
    GAME_HINTS = T.GAME_HINTS.value
    GAME_DIFFICULTY = T.GAMZ_DIFFICULTY.value
    GAME_GRID_SIZE = T.GAME_GRID_SIZE.value
    GAME_VERIFY = T.GAME_VERIFY.value
    GAME_WIN_TITLE = T.GAME_WIN_TITLE.value
    GAME_WIN_MESSAGE = T.GAME_WIN_MESSAGE.value
    GAME_LOSE_TITLE = T.GAME_LOSE_TITLE.value
    GAME_LOSE_MESSAGE = T.GAME_LOSE_MESSAGE.value
    GAME_TRY_AGAIN_MESSAGE = T.GAME_TRY_AGAIN_MESSAGE.value
    GAME_HINTS_SPLASH_MESSAGE = T.GAME_HINTS_SPLASH_MESSAGE.value
